# Generated by Django 2.1.8 on 2019-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.CharField(max_length=64, verbose_name='机器人id')),
                ('version', models.CharField(max_length=64, verbose_name='机器人版本号')),
                ('mode', models.CharField(max_length=64, verbose_name='机器人版本号')),
                ('update_time', models.DateTimeField(verbose_name='机器人版本号')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
                'db_table': 't_publish_setting',
            },
        ),
    ]
