# Generated by Django 2.1.8 on 2019-08-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_robot', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
