# Generated by Django 2.1.8 on 2019-08-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_auto_20190815_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_robot', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
